Update index.html
ssimeetupkorea/vc-data-model pull request #2
Opened 2020-03-25 06:35 UTC by daoauth

4.2 ~ 4.3

2020-03-25 08:50 UTC, aceshim requested changes
자세한 내용은 코멘트 참조 부탁드립니다~

2020-03-25 08:50 UTC, pensivej commented on index.html
> +<em>만약</em> the <code>id</code> <a>속성</a>이 존재한다면:
```suggestion
<em>만약</em> <code>id</code> <a>속성</a>이 존재한다면:
```

2020-03-25 08:50 UTC, pensivej commented on index.html
> +The <code>id</code> <a>속성</a>을 표현할 때 반드시 다른 사용자들이 특정 사물을 표현할 때 사용할 것으로 예상되는 식별자로 표현해야 한다.
속성값에 The id 라고 들어가는게 아니니까 빼는것이 맞을것 같습니다

```suggestion
<code>id</code> <a>속성</a>을 표현할 때 반드시 다른 사용자들이 특정 사물을 표현할 때 사용할 것으로 예상되는 식별자로 표현해야 한다.
```

2020-03-25 08:50 UTC, pensivej commented on index.html
> +The <code>id</code> <a>속성</a>은 반드시 하나의 값만 가져야 한다.
```suggestion
<code>id</code> <a>속성</a>은 반드시 하나의 값만 가져야 한다.
```

2020-03-25 08:50 UTC, pensivej commented on index.html
> +<code>id</code> <a>속성</a> 값은 반드시 단일 <a>URI</a>여야 한다. 역참조되는 경우 <a>URI</a>는 <code>id</code>에 대한 기계판독가능정보를 포함한 문서를 생성하는 것이 권장됩니다.
```suggestion
<code>id</code> <a>속성</a> 값은 반드시 단일 <a>URI</a>여야 한다. 역참조되는 경우 <a>URI</a>는 <code>id</code>에 대한 기계판독가능정보를 포함한 문서를 생성하는 것이 권장된다.
```

2020-03-25 08:50 UTC, pensivej commented on index.html
> +위의 예는 두 가지 유형의 식별자를 사용합니다. 첫 번째는 <a>검증가능한 크리덴셜</a>을 위한 것이며 HTTP 기반 URL을 사용한다. 두 번째는 <a>검증가능한 크리덴셜</a>의 <a>주체</a>(<a>클레임</a>이 관련된 것)를 위한 것이며 <a>DID</a>라고도하는 <a>탈중앙 식별자</a>를 사용한다.
```suggestion
위의 예는 두 가지 유형의 식별자를 사용한다. 첫 번째는 <a>검증가능한 크리덴셜</a>을 위한 것이며 HTTP 기반 URL을 사용한다. 두 번째는 <a>검증가능한 크리덴셜</a>의 <a>주체</a>(<a>클레임</a>이 관련된 것)를 위한 것이며 <a>DID</a>라고도하는 <a>탈중앙 식별자</a>를 사용한다.
```

2020-03-25 08:50 UTC, pensivej commented on index.html
> +본 간행물에 의하면, <a>DIDs</a>는 편리한 <a>검증가능한 크리덴셜</a>이 필요치 않은 새로운 유형의 식별자 아다. 구체적으로 <a>검증가능한 크리덴셜</a>은 <a>DIDs</a>에 의존하지 않으며, <a>DIDs</a>는 <a>검증가능한 크리덴셜</a>에 의존하지 않는다. 그렇지만 많은 <a>검증가능한 크리덴셜</a>이 <a>DIDs</a>
```suggestion
본 간행물에 의하면, <a>DIDs</a>는  새로운 유형의 식별자이지만 <a>검증가능한 크리덴셜</a>이 유용해지기 위해 필수적이지는 않다. 구체적으로 <a>검증가능한 크리덴셜</a>은 <a>DIDs</a>에 의존하지 않으며, <a>DIDs</a>는 <a>검증가능한 크리덴셜</a>에 의존하지 않는다. 그렇지만 많은 <a>검증가능한 크리덴셜</a>이 <a>DIDs</a>를 사용할 것으로 예상되고, 이 규격을 구현하는 소프트웨어 라이브러리는 <a>DIDs</a>를 구현할 필요가 있을 것이다. <a>DID</a> 기반 URL은 <a>주체</a>, <a>발급자</a>, <a>보유자</a>, 크리덴셜 상태 목록, 암호화 키 그리고 <a>검증가능한 크리덴셜</a>과 관련된 기계 판독 가능 정보를 관련된 식별자로 표현하는 데 사용된다.
```

직역을 하면 어려워서 문장의 구성을 조금 바꿔봤습니다

2020-03-25 08:50 UTC, pensivej commented on index.html
> +모든 <a>크리덴셜</a>, <a>프레젠테이션</a>, 그리고 켑슐화된 객채들은 추가정보를 처리할 수 있도록, 더욱 제한된 <a>type들</a> (예를 들어 <code>UniversityDegreeCredential</code>과 같은)을 반드시 명시하거나 연관시켜야 한다.
```suggestion
모든 <a>크리덴셜</a>, <a>프레젠테이션</a>, 그리고 캡슐화된 객채들은 추가정보를 처리할 수 있도록, 더욱 제한된 <a>type들</a> (예를 들어 <code>UniversityDegreeCredential</code>과 같은)을 반드시 명시하거나 연관시켜야 한다.
```

2020-03-25 08:50 UTC, pensivej commented on index.html
> +이 규격에 정의된 캡슐화된 객체(예를 들어 <code>credentialSubject</code>객체와 관련되거나 깊이 중첩된 객체들)들을 처리할 때, 소프트웨어 시스템은 객체를 캡슐화할때 사용된 상위 걔층의<a>type</a> 정보를 사용해야 한다. 구체적으로 <a>크리덴셜</a>과 같은 캡슐화된 객체들은 연관된 객체 <a>type</a>을 전달하여,
```suggestion
이 규격에 정의된 캡슐화된 객체(예를 들어 <code>credentialSubject</code>객체와 관련되거나 깊이 중첩된 객체들)들을 처리할 때, 소프트웨어 시스템은 객체를 캡슐화할때 사용된 상위 계층의<a>type</a> 정보를 사용해야 한다. 구체적으로 <a>크리덴셜</a>과 같은 캡슐화된 객체들은 연관된 객체 <a>type</a>을 전달하여, <a>검증자</a>가 캡슐화 객체의 <a>type</a>에 기초하여 관련 객체의 내용을 신속하게 파악할 수 있어야한다.
```

2020-03-25 08:50 UTC, pensivej commented on index.html
>  For example, a <a>credential</a> object with the <code>type</code> of
영어부분 삭제

2020-03-25 08:50 UTC, pensivej commented on index.html
> +이를 통해 구현자는 <a>검증</a>을 목적으로 <code>type</code> 속성과 관련된 값에 의존할 수 있습니다. <a>types</a> 및 관련 속성은 최소한 사람이 읽을 수 있는 규격으로 문서화 할 것을 기대하고, 가급적 기계판독가능한 설명을 추가합니다.
```suggestion
이를 통해 구현자는 <a>검증</a>을 목적으로 <code>type</code> 속성과 관련된 값에 의존할 수 있다. <a>types</a> 및 관련 속성은 최소한 사람이 읽을 수 있는 규격으로 문서화 할 것을 기대하고, 가급적 기계판독가능한 설명을 추가한다.
```

2020-03-25 08:50 UTC, pensivej commented on index.html
> +이 규격에 기술된 데이터 모델에 사용되는 type 시스템은 type과 데이터와 연결하는 여러가지 방법을 허용합니다. 구현자와 작성자는 Verifiable Credentials Implementation Guidelines[[?VC-IMP-GUIDE]]의 typing에 관한 섹션을 읽어야 합니다.
```suggestion
이 규격에 기술된 데이터 모델에 사용되는 type 시스템은 type과 데이터와 연결하는 여러가지 방법을 허용한다. 구현자와 작성자는 Verifiable Credentials Implementation Guidelines[[?VC-IMP-GUIDE]]의 typing에 관한 섹션을 읽어야 한다.
```

2020-03-25 08:53 UTC, aceshim requested changes
제목을 영어로 바꾸는것
s를 살려서 복수로 적을것인가 단수로 적을것인가 결정 필요

2020-03-25 08:53 UTC, pensivej commented on index.html
>          <h3>Identifiers</h3>
```suggestion
        <h3>식별자</h3>
```

2020-03-25 08:53 UTC, pensivej commented on index.html
>          <h3>Types</h3>
타입

2020-03-31 15:15 UTC, minhoyoo-iotrust requested changes

2020-03-31 15:15 UTC, minhoyoo-iotrust commented on index.html
>        <section>
```suggestion
      <section id="identifiers">
```

2020-03-31 15:15 UTC, minhoyoo-iotrust commented on index.html
> +사람, 제품, 또는 조직과 같은 특정한 것에 대해 표현할때, 다른 사람들이 동일한 것을 표현할 수 있도록 식별자를 사용하는 것이 유용하다. 이 규격에서는 이러한 식별자들에 대한 선택적 <code>id</code> 속성을 정의한다. <code>id</code> <a>속성</a>은 사람, 제품 또는 조직과 같은 객체를 명확하게 참조하기 위한 것이다. <cod
```suggestion
사람, 제품, 또는 조직과 같은 특정한 것에 대해 표현할때, 
다른 사람들이 동일한 것을 표현할 수 있도록 식별자를 사용하는 것이 유용하다. 
이 규격에서는 이러한 식별자들에 대한 선택적 <code>id</code> 속성을 정의한다. 
<code>id</code> <a>속성</a>은 사람, 제품 또는 조직과 같은 객체를 명확하게 참조하기 위한 것이다. 
<code>id</code> <a>속성</a>을 사용하면 
<a>검증가능한 크리덴셜</a>을 통해 특정한 사물을 표현할 수 있게 된다.
```

2020-03-31 15:15 UTC, minhoyoo-iotrust commented on index.html
> +개발자들은 익명성이 요구되는 시나리오에서 식별자가 유해할 수 있다는 것을 기억해야 한다. 그러한 시나리오를 고려할 때 <a href="#identifier-based-correlation"></a> 부분을 주의깊게 읽을 것을 권장한다. 프라이버시 문제를 만들어 내는 다른 유형의 연관메커니즘문서도 <a href="#privacy-considerations"
```suggestion
개발자들은 익명성이 요구되는 시나리오에서 식별자가 유해할 수 있다는 것을 기억해야 한다. 
그러한 시나리오를 고려할 때 <a href="#identifier-based-correlation"></a> 부분을 주의깊게 읽을 것을 권장한다. 
프라이버시 문제를 만들어 내는 다른 유형의 연관메커니즘문서도 
<a href="#privacy-considerations"></a>에서 다루어 진다. 
프라이버시가 중요한 고려사항인 경우 <code>id</code> <a>속성</a>은 생략 될 수 있다.	
```

2020-03-31 15:15 UTC, minhoyoo-iotrust commented on index.html
> +<code>id</code> <a>속성</a> 값은 반드시 단일 <a>URI</a>여야 한다. 역참조되는 경우 <a>URI</a>는 <code>id</code>에 대한 기계판독가능정보를 포함한 문서를 생성하는 것이 권장된다.
```suggestion
<code>id</code> <a>속성</a> 값은 반드시 단일 <a>URI</a>여야 한다. 
역참조되는 경우 <a>URI</a>는 <code>id</code>에 대한 
기계판독가능정보를 포함한 문서를 생성하는 것이 권장된다.
```

2020-03-31 15:15 UTC, minhoyoo-iotrust commented on index.html
> +위의 예는 두 가지 유형의 식별자를 사용한다. 첫 번째는 <a>검증가능한 크리덴셜</a>을 위한 것이며 HTTP 기반 URL을 사용한다. 두 번째는 <a>검증가능한 크리덴셜</a>의 <a>주체</a>(<a>클레임</a>이 관련된 것)를 위한 것이며 <a>DID</a>라고도하는 <a>탈중앙 식별자</a>를 사용한다.
```suggestion
위의 예는 두 가지 유형의 식별자를 사용한다. 
첫 번째는 <a>검증가능한 크리덴셜</a>을 위한 것이며 HTTP 기반 URL을 사용한다. 
두 번째는 <a>검증가능한 크리덴셜</a>의 <a>주체</a>(<a>클레임</a>이 관련된 것)를 위한 것이며 
<a>DID</a>라고도하는 <a>탈중앙 식별자</a>를 사용한다.
```

2020-03-31 15:15 UTC, paromix commented on index.html
> +본 간행물에 의하면, <a>DIDs</a>는  새로운 유형의 식별자이지만 <a>검증가능한 크리덴셜</a>이 유용해지기 위해 필수적이지는 않다. 구체적으로 <a>검증가능한 크리덴셜</a>은 <a>DIDs</a>에 의존하지 않으며, <a>DIDs</a>는 <a>검증가능한 크리덴셜</a>에 의존하지 않는다. 그렇지만 많은 <a>검증가능한 크리덴셜</a>이 <a
```suggestion
본 간행물에 의하면, <a>DIDs</a>는  새로운 유형의 식별자이지만 
<a>검증가능한 크리덴셜</a>의 유용성에 필수는 아니다. 
구체적으로 <a>검증가능한 크리덴셜</a>은 <a>DIDs</a>에 의존하지 않으며, 
<a>DIDs</a>는 <a>검증가능한 크리덴셜</a>에 의존하지 않는다. 
그렇지만 많은 <a>검증가능한 크리덴셜</a>이 <a>DIDs</a>를 사용할 것으로 예상되고, 
이 규격을 구현하는 소프트웨어 라이브러리는 <a>DIDs</a>를 구현할 필요가 있을 것이다. 
<a>DID</a> 기반 URL은 <a>주체</a>, <a>발급자</a>, <a>보유자</a>, 크리덴셜 상태 목록, 암호화 키 
그리고 <a>검증가능한 크리덴셜</a>과 관련된 기계 판독 가능 정보를 관련된 식별자로 표현하는 데 사용된다.
```

2020-03-31 15:15 UTC, paromix commented on index.html
>        <section>
```suggestion
      <section id="types">
```

2020-03-31 15:15 UTC, paromix commented on index.html
>          <h3>Types</h3>
```suggestion
        <h3>타입</h3>
```

2020-03-31 15:15 UTC, paromix commented on index.html
> +이 문서에 지정된 객체들을 처리하는 소프트웨어 시스템은 제공된 <a>검증가능한 크리덴셜</a> 또는 <a>검증가능한 프레젠테이션</a>이 적절한지 여부를 결정하기 위해 <code>type</code>정보를 사용한다. 이 규격은 type정보 표현에 대한 <code>type</code><a>속성</a>을 정의한다.
```suggestion
이 문서에 지정된 객체들을 처리하는 소프트웨어 시스템은 제공된 
<a>검증가능한 크리덴셜</a> 또는 <a>검증가능한 프레젠테이션</a>이 적절한지 여부를 결정하기 위해 
<code>type</code>정보를 사용한다. 
이 규격은 타입 정보 표현에 대한 <code>type</code><a>속성</a>을 정의한다.
```

2020-03-31 15:15 UTC, paromix commented on index.html
> +<a>검증가능한 크리덴셜</a>과 <a>검증가능한 프레젠테이션</a>에는 반드시 <code>type</code><a>속성</a>이 있어야한다. 따라서 <code>type</code><a>속성</a>이 없는 <a>크리덴셜</a>, 또는 <a>프레젠테이션</a>은 <a>검증</a>을 할수 없으므로 <a>검증가능한 크리덴셜</a>이나 <a>검증가능한 프레젠테이
```suggestion
<a>검증가능한 크리덴셜</a>과 <a>검증가능한 프레젠테이션</a>에는 
반드시 <code>type</code><a>속성</a>이 있어야 한다. 
따라서 <code>type</code><a>속성</a>이 없는 <a>크리덴셜</a>, 또는 <a>프레젠테이션</a>은 
<a>검증</a>을 할수 없으므로 <a>검증가능한 크리덴셜</a>이나 <a>검증가능한 프레젠테이션</a>이 아니다.
```

2020-03-31 15:15 UTC, paromix commented on index.html
> +<code>type</code><a>속성</a>의 값은 반드시 맵핑된(<code>@context</code> 속성의 해석을 통해), 하나 또는 이상의 <a>URIs</a>입니다. 만약 복수의 <a>URI</a>들이 제공되었다면, <a>URIs</a>는 순서가 없는 집합으로 해석해야 한다. 개발편의를 위해 문법적 편의성을 반드시 사용해야 한다. 이러한 편의
```suggestion
<code>type</code><a>속성</a>의 값은 반드시 맵핑된(<code>@context</code> 속성의 해석을 통해), 
하나 또는 이상의 <a>URIs</a>다. 
만약 복수의 <a>URI</a>들이 제공되었다면, <a>URIs</a>는 순서가 없는 집합으로 해석해야 한다. 
개발편의를 위해 문법적 편의성을 반드시 사용해야 한다. 
이러한 편의성에는 JSON-LD 용어가 포함될 수 있다. 
<code>type</code>의 각 <a>URI</a>가 역참조되는 경우 
<code>type</code>에 대한 기계판독가능정보가 포함된 문서를 생성하는 것이 권장된다.
```

2020-03-31 15:15 UTC, paromix commented on index.html
> +규격준수에 관련하여, 다음 표에는 객체들이 반드시 가져야 하는 <a>type</a>이 명시되어 있다
```suggestion
규격준수와 관련하여, 다음 표에는 객체들이 반드시 가져야 하는 <a>타입</a>이 명시되어 있다
```

2020-03-31 15:15 UTC, paromix commented on index.html
> +검증가능한 크리덴셜 데이터 모델의 <a>type</a>시스템은 [[JSON-LD]]와 동일하며 <a href="https://www.w3.org/TR/json-ld/#specifying-the-type">Section 5.4:
```suggestion
검증가능한 크리덴셜 데이터 모델의 <a>type</a>시스템은 [[JSON-LD]]와 동일하며 
<a href="https://www.w3.org/TR/json-ld/#specifying-the-type">섹션 5.4:
```

2020-03-31 15:15 UTC, paromix commented on index.html
> +Specifying the Type</a> 그리고 <a href="https://www.w3.org/TR/json-ld/#json-ld-grammar">Section 8: JSON-LD
```suggestion
Specifying the Type</a> 그리고 <a href="https://www.w3.org/TR/json-ld/#json-ld-grammar">섹션 8: JSON-LD
```

2020-03-31 15:15 UTC, paromix commented on index.html
> +<a href="#extensibility"></a> 참조), 이 규격의 <code>@type</code> 키워드를 다른 이름인 <code>type</code>으로 바꾸면 JSON-LD 문서의 이해가 쉬워질 것이다. 애플리케이션 개발자와 문서 작성자는 JSON-LD type 시스템의 세부사항을 이해할 필요는 없지만, 상호운용 가능한 확장성을 지원하고자 하
```suggestion
<a href="#extensibility"></a> 참조), 
이 규격의 <code>@type</code> 키워드를 다른 이름인 <code>type</code>으로 바꾸면 
JSON-LD 문서의 이해가 쉬워질 것이다. 
애플리케이션 개발자와 문서 작성자는 JSON-LD type 시스템의 세부사항을 이해할 필요는 없지만, 
상호운용 가능한 확장성을 지원하고자 하는 규격의 구현자들은 이해해야 한다.
```

2020-03-31 15:15 UTC, paromix commented on index.html
> +모든 <a>크리덴셜</a>, <a>프레젠테이션</a>, 그리고 캡슐화된 객채들은 추가정보를 처리할 수 있도록, 더욱 제한된 <a>type들</a> (예를 들어 <code>UniversityDegreeCredential</code>과 같은)을 반드시 명시하거나 연관시켜야 한다.
```suggestion
모든 <a>크리덴셜</a>, <a>프레젠테이션</a>, 그리고 캡슐화된 객채들은 추가정보를 처리할 수 있도록, 
더욱 제한된 <a>타입</a>들(예를 들어 <code>UniversityDegreeCredential</code>과 같은)을 
반드시 명시하거나 연관시켜야 한다.
```

2020-03-31 15:15 UTC, paromix commented on index.html
> +이 규격에 정의된 캡슐화된 객체(예를 들어 <code>credentialSubject</code>객체와 관련되거나 깊이 중첩된 객체들)들을 처리할 때, 소프트웨어 시스템은 객체를 캡슐화할때 사용된 상위 계층의<a>type</a> 정보를 사용해야 한다. 구체적으로 <a>크리덴셜</a>과 같은 캡슐화된 객체들은 연관된 객체 <a>type</a>을 전달하여,
```suggestion
이 규격에 정의된 캡슐화된 객체
(예를 들어 <code>credentialSubject</code>객체와 관련되거나 깊이 중첩된 객체들)들을 처리할 때, 
소프트웨어 시스템은 객체를 캡슐화할때 사용된 상위 계층의<a>타입</a> 정보를 사용해야 한다. 
구체적으로 <a>크리덴셜</a>과 같은 캡슐화된 객체들은 연관된 객체 <a>타입</a>을 전달하여, 
<a>검증자</a>가 캡슐화 객체의 <a>타입</a>에 기초하여 관련 객체의 내용을 신속하게 파악할 수 있어야한다.
```

2020-03-31 15:15 UTC, paromix commented on index.html
>  For example, a <a>credential</a> object with the <code>type</code> of
```suggestion
```

2020-03-31 15:15 UTC, paromix commented on index.html
>  <code>UniversityDegreeCredential</code>, signals to a <a>verifier</a> that the
```suggestion
```

2020-03-31 15:15 UTC, paromix commented on index.html
>  object associated with the <code>credentialSubject</code> property contains the
```suggestion
```

2020-03-31 15:15 UTC, paromix commented on index.html
>  identifier for the:
```suggestion
```

2020-03-31 15:15 UTC, paromix commented on index.html
> +예를 들어, <code>UniversityDegreeCredential</code>과 같은 <code>type</code>의 <a>크리덴셜</a> 객체는 다음 항목을 위한 <a>식별자</a>가 <code>credentialSubject</code> 속성에 포함되어 있다는 것을 검증자에게 전송한다:
```suggestion
예를 들어, <code>UniversityDegreeCredential</code>과 같은 <code>type</code>의 <a>크리덴셜</a> 객체는 
다음 항목을 위한 <a>식별자</a>가 <code>credentialSubject</code> 속성에 포함되어 있다는 것을 
검증자에게 전송한다:
```

2020-03-31 15:15 UTC, paromix commented on index.html
> +이를 통해 구현자는 <a>검증</a>을 목적으로 <code>type</code> 속성과 관련된 값에 의존할 수 있다. <a>types</a> 및 관련 속성은 최소한 사람이 읽을 수 있는 규격으로 문서화 할 것을 기대하고, 가급적 기계판독가능한 설명을 추가한다.
```suggestion
이를 통해 구현자는 <a>검증</a>을 목적으로 <code>type</code> 속성과 관련된 값에 의존할 수 있다. 
<a>types</a> 및 관련 속성은 최소한 사람이 읽을 수 있는 규격으로 문서화 할 것을 기대하고, 
가급적 기계판독가능한 설명을 추가한다.
```

2020-03-31 15:15 UTC, paromix commented on index.html
> +이 규격에 기술된 데이터 모델에 사용되는 type 시스템은 type과 데이터와 연결하는 여러가지 방법을 허용한다. 구현자와 작성자는 Verifiable Credentials Implementation Guidelines[[?VC-IMP-GUIDE]]의 typing에 관한 섹션을 읽어야 한다.
```suggestion
이 규격에 기술된 데이터 모델에 사용되는 타입 시스템은 타입과 데이터를 연결하는 여러가지 방법을 허용한다. 
구현자와 작성자는 검증가능한 크리덴셜 구현 가이드[[?VC-IMP-GUIDE]]의 타이핑에 관한 섹션을 읽어야 한다.
```

2020-04-09 06:57 UTC, minhoyoo-iotrust requested changes

2020-04-09 06:57 UTC, paromix commented on index.html
> +<a href="#privacy-considerations"></a>에서 다루어 진다.
```suggestion
<a href="#privacy-considerations"></a>에서 다룬다. 
```
번역체를 살짝 피해보면 어떨까 싶습니다.

2020-04-09 06:57 UTC, paromix commented on index.html
> +검증가능한 크리덴셜 데이터 모델의 <a>type</a>시스템은 [[JSON-LD]]와 동일하며
```suggestion
검증가능한 크리덴셜 데이터 모델의 <a>타입</a>시스템은 [[JSON-LD]]와 동일하며 
```

2020-04-09 06:57 UTC, paromix commented on index.html
> +애플리케이션 개발자와 문서 작성자는 JSON-LD type 시스템의 세부사항을 이해할 필요는 없지만,
```suggestion
애플리케이션 개발자와 문서 작성자는 JSON-LD 타입 시스템의 세부사항을 이해할 필요는 없지만, 
```

2020-04-09 06:57 UTC, paromix commented on index.html
> +상호운용 가능한 확장성을 지원하고자 하는 규격의 구현자들은 이해해야 한다.
```suggestion
상호운용 가능한 확장성을 지원하려는 이 규격의 구현자들은 그 내용을 이해해야 한다.
```

2020-04-09 06:57 UTC, paromix commented on index.html
> +<code>id</code> 속성이 가지고 있는 <a>전공</a>
```suggestion
<code>id</code> 속성이 가지고 있는 <a>주체</a>
```

2020-04-09 06:57 UTC, paromix commented on index.html
> +<code>type</code> 속성이 가지고 있는 학점 형식
```suggestion
<code>type</code> 속성이 가지고 있는 학위 형식
```

2020-04-09 06:57 UTC, paromix commented on index.html
> +<code>name</code> 속성이 가지고 있는 학점 타이틀
```suggestion
<code>name</code> 속성이 가지고 있는 학위 타이틀
```

2020-04-09 06:57 UTC, paromix commented on index.html
> +<a>types</a> 및 관련 속성은 최소한 사람이 읽을 수 있는 규격으로 문서화 할 것을 기대하고,
```suggestion
<a>타입</a> 및 관련 속성은 최소한 사람이 읽을 수 있는 규격으로 문서화하는 것과 함께,
```

2020-04-09 06:57 UTC, paromix commented on index.html
> +가급적 기계판독가능한 설명을 추가한다.
```suggestion
가급적 기계판독가능한 설명을 추가해야 한다.
```

2020-04-16 07:34 UTC, minhoyoo-iotrust approved these changes

2020-04-16 11:27 UTC, pensivej commented
좋습니당

2020-04-22 10:06 UTC, aceshim approved these changes

2020-04-22 10:08 UTC, merged