Update Section 5.8
ssimeetupkorea/vc-data-model pull request #3
Opened 2020-03-25 06:43 UTC by hsy822

2020-03-30 11:50 UTC, minhoyoo-iotrust requested changes

2020-03-30 11:50 UTC, paromix commented on index.html
>        <section>
```suggestion
      <section id="zero-knowledge-proofs">
```

2020-04-09 07:12 UTC, minhoyoo-iotrust approved these changes

2020-04-15 02:57 UTC, daoauth approved these changes

2020-04-22 10:09 UTC, merged