Chapter 5.10 - 6.2.1 Translation
ssimeetupkorea/vc-data-model pull request #4
Opened 2020-03-30 03:24 UTC by yusulism

Phase 1 (5.10 - 6.2.1) 번역내용 반영

2020-03-30 12:18 UTC, minhoyoo-iotrust requested changes

2020-03-30 12:18 UTC, minhoyoo-iotrust commented on index.html
>        <section class="informative">
```suggestion
      <section class="informative" id="authorization">
```

2020-03-30 12:18 UTC, minhoyoo-iotrust commented on index.html
> +역할 기반 접근 제어(RBACs)와 속성 기반 접근 제어(ABACs)는 <a>주체</a>가 자원에 접근하는 것을
```suggestion
역할 기반 접근 제어(Role Based Access Controls, RBACs)와 속성 기반 접근 제어(Attribute Based Access Controls, ABACs)는 <a>주체</a>가 자원에 접근하는 것을 
```

2020-03-30 12:18 UTC, minhoyoo-iotrust commented on index.html
>      <section>
```suggestion
    <section id="syntaxes">
```

2020-03-30 12:18 UTC, paromix commented on index.html
>        </ul>
```
<code>id</code> <a>property</a>
<code>issuer</code> <a>property</a>
<code>issuanceDate</code> <a>property</a>
<code>expirationDate</code> <a>property</a>
```

property -> 속성
번역이 필요합니다.

2020-03-30 12:18 UTC, paromix commented on index.html
> +<a href="#core-data-model">코어 데이터 모델</a>, <a href="#basic-concepts">기본개념</a>
```suggestion
<a href="#core-data-model"></a>, <a href="#basic-concepts"></a> 
```

2020-03-30 12:18 UTC, paromix commented on index.html
> +그리고 <a href="#advanced-concepts">고급 개념</a>에서 설명한 데이터 모델은 <a>검증가능한 크리덴셜</a>
```suggestion
그리고 <a href="#advanced-concepts"></a>에서 설명한 데이터 모델은 <a>검증가능한 크리덴셜</a> 
```

2020-03-30 12:18 UTC, paromix commented on index.html
> +섹션 3. <a href="#core-data-model">코어 데이터 모델</a> 에서 설명한 것과 같이 데이터
```suggestion
섹션 3. <a href="#core-data-model"></a> 에서 설명한 것과 같이 데이터 
```

2020-03-30 12:18 UTC, paromix commented on index.html
> +인스턴스는 <code>@context</code> <a>속성</a>의 추가를 통해, JSON(섹션 <a href="#json">JSON</a>)으로 인코딩되는 방식과 동일하게
```suggestion
인스턴스는 <code>@context</code> <a>속성</a>의 추가를 통해, JSON(섹션 <a href="#json"></a>)으로 인코딩되는 방식과 동일하게 
```

2020-03-30 12:18 UTC, paromix commented on index.html
> +그것의 사용은 섹션 <a href="#extensibility">확장성</a>에서 상술하고 있다.
```suggestion
그것의 사용은 섹션 <a href="#extensibility"></a>에서 상술하고 있다.  
```

2020-03-30 12:18 UTC, paromix commented on index.html
> +컨텍스트가 사용 혹은 결합될 수 있다. <code>https://www.w3.org/2018/credentials/v1</code>
```suggestion
컨텍스트가 사용되거나 결합될 수 있다. <code>https://www.w3.org/2018/credentials/v1</code> 
```

2020-03-30 12:18 UTC, paromix commented on index.html
> +에서 확인할 수 있는 <a href="https://www.w3.org/TR/json-ld/#the-context">JSON-LD 컨텍스트</a>는 고정 문서로써 절대 업데이트 되지 않는다.
```suggestion
에서 확인할 수 있는 <a href="https://www.w3.org/TR/json-ld/#the-context">JSON-LD 컨텍스트</a>는 
고정 문서로써 절대 업데이트 되지 않는다. 
```

2020-03-30 12:18 UTC, paromix commented on index.html
> +붙여넣기 함으로써 자신의 소프트웨어 시스템에 <a>검증가능한 크리덴셜</a>을 포함할 수 있도록 설계되었다. 이러한 접근의 디자인 목표는 이기종 소프트웨어 시스템 간 글로벌 상호 운용성을 보장하는 동시에 진입장벽을 낮추는 것이다. 본 섹션에서는 대부분의 개발자가 눈치채지 못할 수 있지만 구현하는 사람에게는 관심이 있을 접근방식들에 대해 설명한다.
```suggestion
붙여넣기 함으로써 자신의 소프트웨어 시스템에 <a>검증가능한 크리덴셜</a>을 포함할 수 있도록 설계되었다. 
이러한 접근의 디자인 목표는 이기종 소프트웨어 시스템 간 글로벌 상호 운용성을 보장하는 동시에 
진입장벽을 낮추는 것이다. 
본 섹션에서는 대부분의 개발자가 눈치채지 못할 수 있지만 
구현하는 사람에게는 관심이 있을 접근방식들에 대해 설명한다. 
```

2020-03-30 12:18 UTC, paromix commented on index.html
> +<code>verifiableCredential</code>과 <code>proof</code> <a>속성</a>은 <em>그래프 컨테이너(Graph Containers)</em>로 처리된다. 이는 다른 개체가 주장하는 데이터 집합을 분리하는데 사용되는 메커니즘이다. 이것은 각 <a>발행자</a>가 제공한 데이터 그래프와 각 그래프에 대한 유래를 보장하기
```suggestion
<code>verifiableCredential</code>과 <code>proof</code> <a>속성</a>은 
<em>그래프 컨테이너(Graph Containers)</em>로 처리된다. 
이는 다른 개체가 주장하는 데이터 집합을 분리하는데 사용되는 메커니즘이다. 
이것은 각 <a>발행자</a>가 제공한 데이터 그래프와 각 그래프에 대한 유래를 보장하기 위해 
<a>검증가능한 크리덴셜</a>을 제시하는 <a>보유자</a>가 제공하는 정보 간의 
적절한 암호학적 구분을 보장한다.
```

2020-03-30 12:18 UTC, paromix commented on index.html
> +[[!JSON-LD]] 1.1의 <code>@protected</code> 속성 기능은 본 규격에서 정의한 용어를 재정의할 수 없도록 하는데 사용된다. 이는 동일한 <code>@context</code> 선언이 <a>검증가능한 크리덴셜</a> 또는 <a>검증가능한 프레젠테이션</a>의 상단에서 이루어지는한, [[!JSON-LD]] 프로세서의 사용 여부와
```suggestion
[[!JSON-LD]] 1.1의 <code>@protected</code> 속성 기능은 
본 규격에서 정의한 용어를 재정의할 수 없도록 하는데 사용된다. 
이는 동일한 <code>@context</code> 선언이 
<a>검증가능한 크리덴셜</a> 또는 <a>검증가능한 프레젠테이션</a>의 상단에서 이루어지는 한, 
[[!JSON-LD]] 프로세서의 사용 여부와 상관없이 
사용자가 이해한 모든 용어에 대한 상호운용성을 보장한다는 의미이다.
```

2020-03-31 15:17 UTC, minhoyoo-iotrust requested changes

2020-03-31 15:17 UTC, paromix commented on index.html
>        </ul>
@yusulism 이 부분은 index.html에서 수정해서 올려주셔야 할 것 같아요. 깃헙 리뷰하는 곳에서 suggest가 안되네요;;;

2020-04-22 11:21 UTC, minhoyoo-iotrust requested changes

2020-04-22 11:21 UTC, paromix commented on index.html
> +역할 기반 접근 제어(Role Based Access Controls, RBACs)와 속성 기반 접근 제어(Attribute Based Access Controls, ABACs)는 <a>주체</a>가 자원에 접근하는 것을
```suggestion
역할 기반 접근 제어(Role Based Access Controls, RBACs)와 속성 기반 접근 제어(Attribute Based Access Controls, ABACs)는 
<a>주체</a>가 자원에 접근하는 것을 
```

2020-04-22 11:21 UTC, paromix commented on index.html
> +워킹 그룹은 이 사양의 작성과정에서 인증의 사용 사례를 고려하였으며, 본 사양의 위에
```suggestion
워킹 그룹은 본 규격의 작성과정에서 인증의 사용 사례를 고려하였으며, 본 규격 위에 
```

2020-04-22 11:21 UTC, paromix commented on index.html
> +섹션 3. <a href="#core-data-model"></a> 에서 설명한 것과 같이 데이터
```suggestion
섹션 3. <a href="#core-data-model"></a>에서 설명한 것과 같이 데이터 
```

2020-04-22 11:21 UTC, paromix commented on index.html
> +이미 JSON을 사용중인 전개된 시스템에 쉽게 통합할 수 있도록 설계되었으며, JSON에서
```suggestion
이미 JSON을 사용하는 것으로 배포된 시스템에 쉽게 통합할 수 있도록 설계되었으며, JSON에서 
```

2020-04-22 11:21 UTC, paromix commented on index.html
> +<code>@id</code>와 <code>@type</code> 키워드는 각각 <code>id</code>와 <code>type</code>으로 구분되어, 개발자가 이 규격을 관용적 JSON으로 사용할 수 있도록 한다.
```suggestion
<code>@id</code>와 <code>@type</code> 키워드는 
각각 <code>id</code>와 <code>type</code>으로 구분되어, 
개발자가 이 규격을 관용적 JSON으로 사용할 수 있도록 한다.
```

2020-04-22 11:21 UTC, paromix commented on index.html
> +정수, 날짜, 측정단위, URL과 같은 데이터 타입은 자동으로 입력되어 그것을 필요로 하는 사용 사례(Use Case)를 위한 강력한 타입 보장을 제공한다.
```suggestion
정수, 날짜, 측정단위, URL과 같은 데이터 타입은 자동으로 입력되어 
그것을 필요로 하는 사용 사례(Use Case)를 위한 강력한 타입 보장을 제공한다.
```

2020-04-22 11:21 UTC, paromix commented on index.html
>          <section>
```suggestion
        <section id="syntactic-sugar">
```

2020-04-22 11:21 UTC, paromix commented on index.html
>      <section class="informative">
```suggestion
    <section class="informative" id="personally-identifiable-information">
```

2020-04-22 11:21 UTC, paromix commented on index.html
>      <section class="informative">
```suggestion
    <section class="informative" id="identifier-based-correlation">
```

2020-04-22 11:21 UTC, paromix commented on index.html
>      <section class="informative">
```suggestion
    <section class="informative" id="signature-based-correlation">
```

2020-04-22 11:21 UTC, paromix commented on index.html
>      <section class="informative">
```suggestion
    <section class="informative" id="long-lived-identifier-based-correlation">
```

2020-04-22 11:21 UTC, paromix commented on index.html
> +함된 <a>검증가능한 크리덴셜</a>의 필드를 식별하여, 이 정보가 공유될 때 <a>보유자</a>에게 경고해야 한다
```suggestion
포함된 <a>검증가능한 크리덴셜</a>의 필드를 식별하여, 이 정보가 공유될 때 <a>보유자</a>에게 경고해야 한다
```

2020-04-22 11:21 UTC, paromix commented on index.html
>      <section class="informative">
```suggestion
    <section class="informative" id="device-fingerprinting">
```

2020-04-22 11:21 UTC, paromix commented on index.html
>      <section class="informative">
```suggestion
    <section class="informative" id="favor-abstract-claims">
```

2020-04-22 12:12 UTC, daoauth approved these changes

2020-04-22 12:36 UTC, minhoyoo-iotrust approved these changes

2020-04-22 12:42 UTC, merged