5.2 ~ 5.3.1 전까지
ssimeetupkorea/vc-data-model pull request #5
Opened 2020-03-30 11:34 UTC by paromix

* 번역 내용 반영
* Respec 에러 수정을 위해 몇몇 용어 정의 링크 추가

2020-04-15 03:01 UTC, daoauth approved these changes

2020-04-22 11:36 UTC, projector301 requested changes

2020-04-22 11:36 UTC, projector301 commented on index.html
>  these extension points.
points, the Verifiable Credentials Extension Registry [[?VC-EXTENSION-REGISTRY]]
provides an unofficial, curated list of extensions that developers can use from
these extension points. - 삭제 부탁드립니다

2020-04-22 11:36 UTC, projector301 commented on index.html
> +가능할 때마다 일회용 <a>검증가능 크리덴셜</a>을 선호함으로써 사생활을 존중하기 위해 노력해야 한다.
<a>검증가능 크리덴셜</a>-> <a>검증가능한 크리덴셜</a>

2020-04-22 11:36 UTC, projector301 commented on index.html
> +일회용 <a>검증가능 크리덴셜</a>을 사용하는 것은 여러가지 이점이 있다.
검증가능 크리덴셜-> 검증가능한 크리덴셜

2020-04-22 11:36 UTC, projector301 commented on index.html
> +첫번째 이점은 <a>검증자</a> 입장에서 <a>검증가능 크리덴셜</a>에 있는 데이터가 최신이라는 것을 확신할 수 있다는 점이다.
검증가능 크리덴셜-> 검증가능한 크리덴셜

2020-04-22 11:36 UTC, projector301 commented on index.html
> +두번째 이점은 <a>보유자</a> 입장에서 만약 수명이 긴 식별자가 <a>검증가능 크리덴셜</a>에 존재하지 않는다면
검증가능 크리덴셜-> 검증가능한 크리덴셜

2020-04-22 11:36 UTC, projector301 commented on index.html
> +<a>발급자</a>, <a>보유자</a>, <a>검증자</a>가 이 명세에게 설명하고 있는 데이터를 처리할 때 인지하고 있어야 하는 보안 고려사항이 아주 많이 있다.
명세에게 -> 명세서에서

2020-04-22 12:07 UTC, projector301 commented on index.html
>  provides an unofficial, curated list of extensions that developers can use from
```suggestion

```

2020-04-22 12:07 UTC, projector301 commented on index.html
>  points, the Verifiable Credentials Extension Registry [[?VC-EXTENSION-REGISTRY]]
```suggestion

```

2020-04-23 16:43 UTC, projector301 approved these changes

2020-04-24 13:40 UTC, daoauth approved these changes

2020-04-24 13:45 UTC, merged