Modified 5.6, 5.7 and 5.9 sections
ssimeetupkorea/vc-data-model pull request #7
Opened 2020-04-01 10:55 UTC by Hyeongcheol-An

5.6-7, 5.9 번역본

2020-04-01 12:16 UTC, Hyeongcheol-An commented
7.8-10 번역본 추가

2020-04-09 07:26 UTC, minhoyoo-iotrust requested changes

2020-04-09 07:26 UTC, paromix commented on index.html
> +이용약관은 <a>발급자</a> 또는 <a></a>보유자가 <a>검증가능한 크리덴셜</a> 또는
```suggestion
이용약관은 <a>발급자</a> 또는 <a>보유자</a>가 <a>검증가능한 크리덴셜</a> 또는 
```

2020-04-09 07:26 UTC, paromix commented on index.html
> +<a>발급자</a>는 사용 약관을 <a>검증가능한 크리덴셜</a>에 배치한다.
```suggestion
<a>발급자</a>는 이용약관을 <a>검증가능한 크리덴셜</a>에 배치한다. 
```

2020-04-09 07:26 UTC, paromix commented on index.html
> +본 명세서에서는 이용약관 정보를 표현하기 위한 <a>termsOfUse</a> <a>속성</a>을 정의한다.
```suggestion
본 명세서에서는 이용약관 정보를 표현하기 위한 <code>termsOfUse</code> <a>속성</a>을 정의한다.
```

2020-04-09 07:26 UTC, paromix commented on index.html
> +<a>프리젠테이션</a>을 발행 한 하나 이상의 이용 약관 정책을 지정해야만 한다.
```suggestion
<a>프레젠테이션</a>을 발행 한 하나 이상의 이용 약관 정책을 지정해야만 한다. 
```

2020-04-09 07:26 UTC, paromix commented on index.html
> +각 <code>termsOfUse</code> 값은 <a>유형</a>을 지정해야 하고
```suggestion
각 <code>termsOfUse</code> 값은 <a>타입</a>을 지정해야 하고 
```

2020-04-09 07:26 UTC, paromix commented on index.html
> +각 이용 약관의 정확한 내용은 특정 code>termsOfUse</code> <a>유형</a> 정의에 의해
```suggestion
각 이용 약관의 정확한 내용은 특정 code>termsOfUse</code> <a>타입</a> 정의에 의해 
```

2020-04-09 07:26 UTC, paromix commented on index.html
> +        <pre class="example nohighlight" title="보유자에 의한 termsOfUse 특성 사용">
```suggestion
        <pre class="example nohighlight" title="보유자에 의한 termsOfUse 속성 사용">
```

2020-04-09 07:26 UTC, paromix commented on index.html
> +각 증거 체계는 <a>유형</a>별로 식별된다.
```suggestion
각 증거 체계는 <a>타입</a>별로 식별된다.
```

2020-04-09 07:26 UTC, paromix commented on index.html
> +<code>evidence</code> <a>유형</a> 정의에 의해 결정된다.
```suggestion
<code>evidence</code> <a>타입</a> 정의에 의해 결정된다.
```

2020-04-09 07:26 UTC, paromix commented on index.html
> +General Data Protection Regulation (GDPR)을 포함한 여러 관할권의 규정에 의해
```suggestion
GDPR (General Data Protection Regulation)을 포함한 여러 관할권의 규정에 의해 
```
HIPAA와 표현 형식을 맞추는 것이 좋을 것 같습니다.

2020-04-09 19:49 UTC, Hyeongcheol-An commented
수정사항 반영했습니다.

2020-04-16 07:39 UTC, minhoyoo-iotrust approved these changes

2020-04-22 11:54 UTC, daoauth approved these changes

2020-04-22 11:55 UTC, merged