Added 4.4~4.8 and 10~A.3
ssimeetupkorea/vc-data-model pull request #8
Opened 2020-04-20 04:40 UTC by projector301

4.4~4.8 번역본 추가
10~A.3 번역본 추가

2020-04-22 11:01 UTC, daoauth commented on index.html
>        <section>
section id를 추가 id="credential-subject"

2020-04-22 11:38 UTC, minhoyoo-iotrust requested changes
@daoauth 님과 같은 곳을 하는 것 같아서 일단 여기까지 합니다.

2020-04-22 11:38 UTC, paromix commented on index.html
>        <section>
```suggestion
      <section id="credential-subject">
```

2020-04-22 11:38 UTC, paromix commented on index.html
> +<a>검증 가능한 크리덴셜</a> 에는 하나 이상의 <a>주체들</a>에 대한 <a>클레임이</a> 포함된다.
```suggestion
<a>검증가능한 크리덴셜</a> 에는 하나 이상의 <a>주체들</a>에 대한 <a>클레임이</a> 포함된다. 
```

2020-04-22 11:38 UTC, paromix commented on index.html
> +이 규격은 하나이상의 <a>주체들</a>에 대한 <a>클레임</a>의 <a>표현</a>의 <code>credentialSubject</code>
```suggestion
이 규격은 하나 이상의 <a>주체들</a>에 대한 <a>클레임</a>을 <a>표현</a>하기 위한 항목인
<code>credentialSubject</code> 
```

2020-04-22 11:38 UTC, paromix commented on index.html
> +속성을 정의한다.
```suggestion
<a>속성</a>을 정의한다.
```

2020-04-22 11:38 UTC, paromix commented on index.html
> +<a>검증 가능한 크리덴셜</a>에는 무조건 <code>credentialSubject</code> <a>속성</a>이 있어야 한다.
```suggestion
<a>검증가능한 크리덴셜</a>에는 무조건 <code>credentialSubject</code> <a>속성</a>이 있어야 한다.
```

2020-04-22 11:38 UTC, paromix commented on index.html
> +<code>credentialSubject</code> <a>속성</a>의 값은 <a>검증 가능한 크리덴셜</a>의 <a>주체</a>와 각각 관련된 하나 이상의 특성을 포함하는
```suggestion
<code>credentialSubject</code> <a>속성</a>의 값은 <a>검증가능한 크리덴셜</a>의 <a>주체</a>와 
각각 관련된 하나 이상의 특성을 포함하는 
```

2020-04-22 11:38 UTC, paromix commented on index.html
>  a set of objects that contain one or more properties that are each related to a
```suggestion
```

2020-04-22 11:38 UTC, paromix commented on index.html
>  <a>subject</a> of the <a>verifiable credential</a>. Each object MAY contain an
```suggestion
```

2020-04-22 11:38 UTC, paromix commented on index.html
>  <code>id</code>, as described in Section <a href="#identifiers"></a>.
```suggestion
```

2020-04-22 11:38 UTC, paromix commented on index.html
> +		  객체 세트로 정의된다. <a href="#식별자들"></a>에 설명 된대로 각 객체에는 <code>id</code>가 포함될 수도 있다.
```suggestion
객체 세트로 정의된다. <a href="#identifiers"></a>에 설명 된대로 각 객체에는 <code>id</code>가 포함될 수도 있다.
```

2020-04-22 11:38 UTC, paromix commented on index.html
>        <section>
```suggestion
      <section id="issuer">
```

2020-04-22 11:38 UTC, paromix commented on index.html
> +이 규격은 <a>검증 가능한 크리덴셜</a>의 <a>발급자</a>를 표현하기 위한 속성을 정의한다.
```suggestion
이 규격은 <a>검증가능한 크리덴셜</a>의 <a>발급자</a>를 표현하기 위한 속성을 정의한다.
```

2020-04-22 11:38 UTC, paromix commented on index.html
> +<a>검증 가능한 크리덴셜</a>은 무조건 <code>issuer</code> <a>속성</a>이 있어야 한다.
```suggestion
<a>검증가능한 크리덴셜</a>은 무조건 <code>issuer</code> <a>속성</a>이 있어야 한다.
```

2020-04-22 11:38 UTC, paromix commented on index.html
> +<code>issuer</code> 또는 해당 <code>id</code>의 <a>URI</a>는 역 참조 된 경우 <a>크리덴셜</a>에 표시된 정보를 <a>검증</a>하는 데 사용할 수 있는
```suggestion
<code>issuer</code> 또는 해당 <code>id</code>의 <a>URI</a>는 역 참조 된 경우 
<a>크리덴셜</a>에 표시된 정보를 <a>검증</a>하는 데 사용할 수 있는 
```

2020-04-22 11:38 UTC, paromix commented on index.html
> +<a>issuer</a>에 대한 machine-readable 정보를 포함하는 문서를 생성하는 URI 여야 한다.
```suggestion
<a>issuer</a>에 대한 기계판독 가능한 정보를 포함하는 문서를 생성하는 URI 여야 한다.
```

2020-04-22 11:38 UTC, paromix commented on index.html
>        <section>
```suggestion
      <section id="issuance-date">
```

2020-04-22 11:38 UTC, paromix commented on index.html
> +<code>issuanceDate</code> <a>속성</a>의 값은 <a>크리덴셜</a>이 유효한 날짜와 시간을 나타내는 [RFC3339] 결합 날짜 및 시간
```suggestion
<code>issuanceDate</code> <a>속성</a>의 값은 
<a>크리덴셜</a>이 유효한 날짜와 시간을 나타내는 [[!RFC3339]] 결합 날짜 및 시간 
```

2020-04-22 11:38 UTC, paromix commented on index.html
> +        <pre class="example nohighlight" title="issuanceDate 특성 사용">
```suggestion
        <pre class="example nohighlight" title="issuanceDate 속성 사용">
```

2020-04-22 11:38 UTC, paromix commented on index.html
> +이 스펙의 다음 버전은 <code>validFrom</code> <a>특성</a>을 추가하고 새로운 <code>issued</code> 된 <a>특성</a>을 위해 <code>issuanceDate</code> <a>특성</a>을
```suggestion
이 스펙의 다음 버전은 <code>validFrom</code> <a>속성</a>을 추가하고 
새로운 <code>issued</code> 된 <a>속성</a>을 위해 <code>issuanceDate</code> <a>속성</a>을 
```

2020-04-22 11:38 UTC, paromix commented on index.html
> +더 이상 사용하지 않을 것으로 예상된다. 두 속성의 값 범위는 [RFC3339] 결합 날짜 및 시간 문자열로 유지
```suggestion
더 이상 사용하지 않을 것으로 예상된다. 두 속성의 값 범위는 [[?RFC3339]] 결합 날짜 및 시간 문자열로 유지 
```

2020-04-22 11:38 UTC, paromix commented on index.html
> +될 것으로 예상한다. 구현자는 <code>validFrom</code> 및 <code>issued</code> <a>속성</a>을 예약하고 다른 목적으로 사용하지 않는 것이 좋다.
```suggestion
될 것으로 예상한다. 구현자는 <code>validFrom</code> 및 <code>issued</code> <a>속성</a>을 예약하고 
다른 목적으로 사용하지 않는 것이 좋다.
```

2020-04-22 11:44 UTC, daoauth commented on index.html
> +<a>검증 가능한 크리덴셜</a> 에는 하나 이상의 <a>주체들</a>에 대한 <a>클레임이</a> 포함된다.
~~~
<a>검증가능한 크리덴셜</a>, <a>주체</a>들, <a>클레임</a>이

"검증 가능한"을 "검증가능한"으로 일괄 변경이 필요합니다.
~~~

2020-04-22 11:44 UTC, daoauth commented on index.html
> +이 규격은 하나이상의 <a>주체들</a>에 대한 <a>클레임</a>의 <a>표현</a>의 <code>credentialSubject</code>
~~~
<a>주체</a>들
~~~

2020-04-22 11:44 UTC, daoauth commented on index.html
>        <section>
section id를 추가 id="issuer"

2020-04-22 11:44 UTC, daoauth commented on index.html
> +<a>issuer</a>에 대한 machine-readable 정보를 포함하는 문서를 생성하는 URI 여야 한다.
~~~
machine-readable 정보 => 기계 판독 가능 정보
~~~

2020-04-22 11:44 UTC, daoauth commented on index.html
>        <section>
~~~
<section id="issuance-date">
~~~

2020-04-22 11:44 UTC, daoauth commented on index.html
> +<code>issuanceDate</code> <a>속성</a>의 값은 <a>크리덴셜</a>이 유효한 날짜와 시간을 나타내는 [RFC3339] 결합 날짜 및 시간
[[!RFC3339]]

2020-04-22 11:44 UTC, daoauth commented on index.html
> +더 이상 사용하지 않을 것으로 예상된다. 두 속성의 값 범위는 [RFC3339] 결합 날짜 및 시간 문자열로 유지
[[?RFC3339]]

2020-04-22 11:44 UTC, daoauth commented on index.html
>        <section>
~~~
<section id="proofs-signatures">
~~~

2020-04-22 11:44 UTC, daoauth commented on index.html
>        <section>
~~~
<section id="expiration">
~~~

2020-04-22 11:44 UTC, daoauth commented on index.html
> +이 사양에서는 <a>크리덴셜</a> 만료 정보 표현을위한 <code>expirationDate</code> <a>속성</a>을 정의합니다.
정의합니다. -> 정의한다.

2020-04-22 11:44 UTC, daoauth commented on index.html
> +나타내는 [[!RFC3339]] 결합 날짜 및 시간 문자열의 문자열 값이어야합니다.
값이어야합니다. -> 값이어야 합니다.

2020-04-22 11:44 UTC, daoauth commented on index.html
>    <section class="informative">
~~~
<section class="informative" id="internationalization-considerations">
~~~

2020-04-22 11:44 UTC, daoauth commented on index.html
>      <section class="informative">
~~~
<section class="informative" id="language-and-base-direction">
~~~

2020-04-22 11:44 UTC, daoauth commented on index.html
> +	      JSON-LD를 사용하는 구현자는 국제화 된 <a>특성</a>을 정의하는 JSON-LD 컨텍스트를 <a href="#extensibility">extend</a>하고 JSON-LD의 범위
~~~
<a>특성</a> -> <a>속성</a>
~~~

2020-04-22 11:44 UTC, daoauth commented on index.html
>  doing this is shown below.
원문이 남아 있습니다.

2020-04-22 11:44 UTC, daoauth commented on index.html
>    <section class="appendix informative">
~~~
<section class="appendix informative" id="validation">
~~~

2020-04-22 11:44 UTC, daoauth commented on index.html
>        <section class="informative">
~~~
<section class="informative" id="credential-subject">
~~~

2020-04-22 11:44 UTC, daoauth commented on index.html
>        <section class="informative">
~~~
<section class="informative" id="issuance-date">
~~~

2020-04-22 11:44 UTC, daoauth commented on index.html
>        <section class="informative">
~~~
<section class="informative" id="issuer">
~~~

2020-04-22 12:18 UTC, projector301 commented on index.html
> +이 규격은 하나이상의 <a>주체들</a>에 대한 <a>클레임</a>의 <a>표현</a>의 <code>credentialSubject</code>
```suggestion
이 규격은 하나이상의 <a>주체</a>들에 대한 <a>클레임</a>의 <a>표현</a>의 <code>credentialSubject</code> 
```

2020-04-22 12:18 UTC, projector301 commented on index.html
>        <section>
```suggestion
      <section id="proofs-signatures">
```

2020-04-22 12:18 UTC, projector301 commented on index.html
>        <section>
```suggestion
      <section id="expiration">
```

2020-04-22 12:18 UTC, projector301 commented on index.html
> +이 사양에서는 <a>크리덴셜</a> 만료 정보 표현을위한 <code>expirationDate</code> <a>속성</a>을 정의합니다.
```suggestion
이 사양에서는 <a>크리덴셜</a> 만료 정보 표현을위한 <code>expirationDate</code> <a>속성</a>을 정의한다.
```

2020-04-22 12:18 UTC, projector301 commented on index.html
> +나타내는 [[!RFC3339]] 결합 날짜 및 시간 문자열의 문자열 값이어야합니다.
```suggestion
나타내는 [[!RFC3339]] 결합 날짜 및 시간 문자열의 문자열 값이어야 합니다.
```

2020-04-22 12:18 UTC, projector301 commented on index.html
>    <section class="informative">
```suggestion
  <section class="informative" id="internationalization-considerations">
```

2020-04-22 12:18 UTC, projector301 commented on index.html
>      <section class="informative">
```suggestion
    <section class="informative" id="language-and-base-direction">
```

2020-04-22 12:18 UTC, projector301 commented on index.html
> +	      JSON-LD를 사용하는 구현자는 국제화 된 <a>특성</a>을 정의하는 JSON-LD 컨텍스트를 <a href="#extensibility">extend</a>하고 JSON-LD의 범위
```suggestion
	      JSON-LD를 사용하는 구현자는 국제화 된 <a>속성</a>을 정의하는 JSON-LD 컨텍스트를 <a href="#extensibility">extend</a>하고 JSON-LD의 범위 
```

2020-04-22 12:18 UTC, projector301 commented on index.html
>    <section class="appendix informative">
```suggestion
  <section class="appendix informative" id="validation">
```

2020-04-22 12:18 UTC, projector301 commented on index.html
>        <section class="informative">
```suggestion
      <section class="informative" id="credential-subject">
```

2020-04-22 12:18 UTC, projector301 commented on index.html
>        <section class="informative">
```suggestion
      <section class="informative" id="issuer">
```

2020-04-22 12:18 UTC, projector301 commented on index.html
>        <section class="informative">
```suggestion
     <section class="informative" id="issuance-date">
```

2020-04-22 12:18 UTC, projector301 commented on index.html
>  doing this is shown below.
```suggestion

```

2020-04-22 12:18 UTC, projector301 commented on index.html
>  and <code>dir</code>, respectively. An example of a JSON-LD Context snippet
```suggestion

```

2020-04-22 12:18 UTC, projector301 commented on index.html
>  <code>@direction</code> keywords to <code>value</code>, <code>lang</code>,
```suggestion

```

2020-04-22 12:22 UTC, projector301 commented on index.html
>        <section>
```suggestion
      <section id="credential-subject">
```

2020-04-22 12:26 UTC, projector301 commented on index.html
>        </section>
```suggestion
      <section id="credential-subject">
```

2020-04-22 12:26 UTC, projector301 commented on index.html
>  Implementers utilizing JSON-LD are strongly urged to
```suggestion

```

2020-04-22 12:26 UTC, projector301 commented on index.html
>  <a href="#extensibility">extend</a> the JSON-LD Context defining the
```suggestion

```

2020-04-22 12:26 UTC, projector301 commented on index.html
>  internationalized <a>property</a> and use the Scoped Context feature of JSON-LD
```suggestion

```

2020-04-22 12:26 UTC, projector301 commented on index.html
>  to alias the <code>@value</code>, <code>@language</code>, and
```suggestion

```

2020-04-22 13:52 UTC, daoauth approved these changes

2020-04-24 13:52 UTC, daoauth approved these changes

2020-04-27 05:42 UTC, minhoyoo-iotrust requested changes

2020-04-27 05:42 UTC, paromix commented on index.html
> +<code>issuer</code> <a>특성</a>값은 JWK (for example, <code>"https://example.com/keys/foo.jwk"</code>)
```suggestion
<code>issuer</code> <a>특성</a>값은 JWK (예를 들어, <code>"https://example.com/keys/foo.jwk"</code>) 
```

2020-04-27 05:42 UTC, paromix commented on index.html
> +또는 a <a>DID</a> (for example, <code>"did:example:abfe13f712120431c276e12ecab"</code>)이 될 수 있다.
```suggestion
또는 a <a>DID</a> (예를 들어, <code>"did:example:abfe13f712120431c276e12ecab"</code>)이 될 수 있다.	
```

2020-04-27 05:42 UTC, paromix commented on index.html
> +이 사양은 <a>검증 가능한 크리덴셜</a>과 함께 사용하기위한 단일 증명 메커니즘을 표준화하거나 권장하지 않는다.
```suggestion
이 사양은 <a>검증가능한 크리덴셜</a>과 함께 사용하기위한 단일 증명 메커니즘을 표준화하거나 권장하지 않는다. 
```

2020-04-27 05:42 UTC, paromix commented on index.html
> +나타내는 [[!RFC3339]] 결합 날짜 및 시간 문자열의 문자열 값이어야 합니다.
```suggestion
나타내는 [[!RFC3339]] 결합 날짜 및 시간 문자열의 문자열 값이어야 한다.
```

2020-04-27 05:42 UTC, paromix commented on index.html
> +<a>속성</a>과의 호환성을 유지해야한다. 구현자는 <code>validUntil</code> <a>속성</a>이 이미 용도결정이 되어 있고 다른 용도로 사용하지 않는 것이 좋다.
```suggestion
<a>속성</a>과의 호환성을 유지해야한다. 
구현자는 <code>validUntil</code> <a>속성</a>이 이미 용도결정이 되어 있고 
다른 용도로 사용하지 않는 것이 좋다.
```

2020-04-27 05:42 UTC, paromix commented on index.html
> +구현자는이 사양에 설명 된 데이터를 게시 할 때 여러 국제화 고려 사항을 알고 있어야한다. 웹 표준 또는 프로토콜 구현과 마찬가지로 국제화를 무시하면 데이터의 다른 언어와 사회에서 데이터를 생성하고 소비하기가 어려워 지므로 사양의 적용 가능성이 제한되고 표준으로서의 가치가 크게 떨어진다.
```suggestion
구현자는 이 사양에 설명 된 데이터를 게시 할 때 여러 국제화 고려 사항을 알고 있어야 한다. 
웹 표준 또는 프로토콜 구현과 마찬가지로 국제화를 무시하면 
데이터의 다른 언어와 사회에서 데이터를 생성하고 소비하기가 어려워지므로 
사양의 적용 가능성이 제한되고 표준으로서의 가치가 크게 떨어진다.
```

2020-04-27 05:42 UTC, paromix commented on index.html
> +구현자는 국제화를 지원하기 위해 텍스트에 대한 신뢰할 수있는 메타 데이터를 제공하는 W3C 국제화 활동에서 발행 한 <em>웹에서 문자열 : 언어 및 방향 메타 데이터</em> 문서 [[STRING-META]] 읽기를 권장한다. 국제화 고려 사항에 대한 최신 정보를 얻으려면 구현자는 확인 가능한 자격 증명 구현 지침 [[VC-IMP-GUIDE]] 문서를
```suggestion
구현자는 국제화를 지원하기 위해 텍스트에 대한 신뢰할 수 있는 메타 데이터를 제공하는 
W3C 국제화 활동에서 발행 한 
<em>웹에서 문자열 : 언어 및 방향 메타 데이터</em> 문서 [[STRING-META]] 읽기를 권장한다. 
국제화 고려 사항에 대한 최신 정보를 얻으려면 
구현자는 확인 가능한 자격 증명 구현 지침 [[VC-IMP-GUIDE]] 문서를 읽어야한다.
```

2020-04-27 05:42 UTC, paromix commented on index.html
> +이 섹션에서는이 데이터 모델을 사용할 때 고려해야 할 일반적인 국제화 고려 사항에 대해 간략하게 설명하고 있으며 구현자가 관심 있을 <em>웹에서 문자열 : 언어 및 방향 메타 데이터</em> 문서 [[STRING-META]]의 특정 부분을 강조하기 위해 구현되었다.
```suggestion
이 섹션에서는이 데이터 모델을 사용할 때 고려해야 할 일반적인 국제화 고려 사항에 대해 간략하게 설명하고 있으며 
구현자가 관심 있을 <em>웹에서 문자열 : 언어 및 방향 메타 데이터</em> 문서 [[STRING-META]]의 
특정 부분을 강조하기 위해 구현되었다.
```

2020-04-27 05:42 UTC, paromix commented on index.html
> +데이터 퍼블리셔는 <em>웹에서 문자열 : 언어 및 방향 메타 데이터</em> 문서 [[STRING-META]]의 교차 구문 표현식 섹션을 읽고 [[JSON-LD]], [[JSON]] 및 CBOR [[?RFC7049]]와 같이 여러 표현식 구문에서 언어 및 기본 방향 정보를 표현할 수 있도록하는 것이 좋다.
```suggestion
데이터 퍼블리셔는 <em>웹에서 문자열 : 언어 및 방향 메타 데이터</em> 문서 [[STRING-META]]의 
교차 구문 표현식 섹션을 읽고 [[JSON-LD]], [[JSON]] 및 CBOR [[?RFC7049]]와 같이 여러 표현식 구문에서 
언어 및 기본 방향 정보를 표현할 수 있도록 하는 것이 좋다.
```

2020-04-27 05:42 UTC, paromix commented on index.html
> +일반적인 디자인 패턴은 언어 및 선택적으로 특정 기준 방향으로 태그가 지정된 텍스트 문자열을 표현할 때 다음 마크 업 템플릿을 사용하는 것이다.
```suggestion
일반적인 디자인 패턴은 언어 및 선택적으로 특정 기준 방향으로 
태그가 지정된 텍스트 문자열을 표현할 때 다음 마크 업 템플릿을 사용하는 것이다.
```

2020-04-27 05:42 UTC, paromix commented on index.html
> +많은 시스템에서 텍스트 문자열의 첫 번째 문자를 사용하여 텍스트 방향을 결정하므로 위의 텍스트는 언어와 방향을 명시 적으로 표현하지 않고 왼쪽에서 오른쪽으로 잘못 표시된다.
```suggestion
많은 시스템에서 텍스트 문자열의 첫 번째 문자를 사용하여 텍스트 방향을 결정하므로 
위의 텍스트는 언어와 방향을 명시적으로 표현하지 않고 왼쪽에서 오른쪽으로 잘못 표시된다.
```

2020-04-27 05:42 UTC, paromix commented on index.html
> +	      JSON-LD를 사용하는 구현자는 국제화 된 <a>속성</a>을 정의하는 JSON-LD 컨텍스트를 <a href="#extensibility">extend</a>하고 JSON-LD의 범위
```suggestion
JSON-LD를 사용하는 구현자는 
국제화 된 <a>속성</a>을 정의하는 JSON-LD 컨텍스트를 <a href="#extensibility">extend</a>하고 
JSON-LD의 범위 
```

2020-04-27 05:42 UTC, paromix commented on index.html
> +	      지정된 컨텍스트 기능을 사용하여 <code>@value</code>, <code>@language</code> 및 <code>@direction</code> 키워드를 <code>value</code>, <code>lang</code> 및 <code>dir</code>로 별명
```suggestion
지정된 컨텍스트 기능을 사용하여 
<code>@value</code>, <code>@language</code> 및 <code>@direction</code> 키워드를 
<code>value</code>, <code>lang</code> 및 <code>dir</code>로 별명 
```

2020-04-27 05:42 UTC, paromix commented on index.html
> +	      지정해야한다. 각기. 이를 수행하는 JSON-LD 컨텍스트 스니펫의 예는 다음과 같다.
```suggestion
지정해야한다. 각기. 이를 수행하는 JSON-LD 컨텍스트 스니펫의 예는 다음과 같다.
```

2020-04-27 05:42 UTC, paromix commented on index.html
> +여러 언어, 기본 방향 및 주석이 단일 자연 언어 문자열로 사용되는 경우 일반적으로 더 복잡한 메커니즘이 필요하다. HTML과 같은 마크 업 언어를 사용하여 여러 언어와 기본 방향으로 텍스트를 인코딩 할 수 있다. <code>rdf : HTML</code> 데이터 유형을 사용하여 이러한 값을 JSON-LD로 정확하게 인코딩 할 수도 있다.
```suggestion
여러 언어, 기본 방향 및 주석이 단일 자연 언어 문자열로 사용되는 경우 
일반적으로 더 복잡한 메커니즘이 필요하다. 
HTML과 같은 마크 업 언어를 사용하여 여러 언어와 기본 방향으로 텍스트를 인코딩 할 수 있다. 
<code>rdf : HTML</code> 데이터 유형을 사용하여 이러한 값을 JSON-LD로 정확하게 인코딩 할 수도 있다.
```

2020-04-27 05:42 UTC, paromix commented on index.html
> +		HTML을 맹목적으로 처리하면 데이터 생성 프로세스 중 공격자가 어느 시점에 삽입 한 <code>script</code> 태그가 실행될 수 있으므로이 데이터 모델을 사용할 때 보안 공격 영역이 증가한다.
```suggestion
HTML을 맹목적으로 처리하면 데이터 생성 프로세스 중 공격자가 어느 시점에 삽입 한 
<code>script</code> 태그가 실행될 수 있으므로 이 데이터 모델을 사용할 때 보안 공격 영역이 증가한다.
```

2020-04-27 05:42 UTC, paromix commented on index.html
> +구현자가 특정 사용 사례를 해결하기 위해 HTML 또는 실행 가능한 스크립트를 포함 할 수있는 다른 마크 업 언어를 사용해야한다고 생각하는 경우, 구현자는 공격자가 어떻게 마크 업을 사용하여 마크 업 소비자에 대한 인젝션 공격을 마운트 하는지 분석 후 식별된 공격에 대한 완화를 배포 한다.
```suggestion
구현자가 특정 사용 사례를 해결하기 위해 
HTML 또는 실행 가능한 스크립트를 포함 할 수있는 다른 마크 업 언어를 사용해야한다고 생각하는 경우, 
구현자는 공격자가 어떻게 마크 업을 사용하여 마크 업 소비자에 대한 인젝션 공격을 마운트 하는지 분석 후 
식별된 공격에 대한 완화를 배포 한다. 
```

2020-04-27 05:42 UTC, paromix commented on index.html
> +<a>보유자</a>가 제시 한 <a>검증 가능한 크리덴셜</a>에서 각 <code>credentialSubject</code>의 <a>id</a> <a>특성</a>과 연관된 값은 <a>검증자</a>에게
```suggestion
<a>보유자</a>가 제시 한 <a>검증 가능한 크리덴셜</a>에서 
각 <code>credentialSubject</code>의 <a>id</a> <a>특성</a>과 연관된 값은 <a>검증자</a>에게 
```

2020-04-27 05:42 UTC, paromix commented on index.html
> +인증 및 WebAuthn이 <a>검증 가능한 크리덴셜</a>로 작동하는 방법에 대한 자세한 내용은 검증 가능한 크리덴셜 구현 지침 [[VC-IMP-GUIDE]] 문서를 참조.
```suggestion
인증 및 WebAuthn이 <a>검증 가능한 크리덴셜</a>로 작동하는 방법에 대한 자세한 내용은 
검증 가능한 크리덴셜 구현 지침 [[VC-IMP-GUIDE]] 문서를 참조.
```

2020-04-27 05:42 UTC, paromix commented on index.html
> +포함 된 정보를 게시 할 수 있습니다. 이 메타 데이터는 <a>검증 가능한 크리덴셜</a>에서 증명을 확인할 때 관련이 있습니다.
```suggestion
포함 된 정보를 게시 할 수 있다. 이 메타 데이터는 <a>검증 가능한 크리덴셜</a>에서 증명을 확인할 때 관련이 있다.
```

2020-04-27 05:42 UTC, paromix commented on index.html
> +<code>issuanceDate</code>는 <a>검증자</a>의 예상 범위 내에 있어야한다. 예를 들어, <a>검증자</a>는 <a>검증 가능한 크리덴셜</a>의 발급 날짜가 미래에 있지 않은지 확인할 수 있다.
```suggestion
<code>issuanceDate</code>는 <a>검증자</a>의 예상 범위 내에 있어야한다. 
예를 들어, <a>검증자</a>는 <a>검증 가능한 크리덴셜</a>의 발급 날짜가 미래에 있지 않은지 확인할 수 있다.
```

2020-04-27 05:44 UTC, minhoyoo-iotrust requested changes

2020-04-27 05:44 UTC, paromix commented on index.html
> +이 규격은 두가지 종류의 메커니즘을 식별한다: 외부 증명과 내장된 증명. <dfn>외부 프루프</dfn>은 <a href="#json-web-token"></a>섹션에 자세히
```suggestion
이 규격은 두가지 종류의 메커니즘을 식별한다: 외부 증명과 내장된 증명. 
<dfn>외부 프루프</dfn>은 <a href="#json-web-token"></a>섹션에 자세히 
```

2020-04-27 05:44 UTC, minhoyoo-iotrust approved these changes

2020-04-27 05:45 UTC, merged