10.C.1.1~10.C.6
ssimeetupkorea/vc-data-model pull request #9
Opened 2020-04-21 08:55 UTC by sekwangoh

10.C.1.1~10.C.6 pull request

2020-04-22 10:52 UTC, projector301 reviewed
예시 번역 필요합니다.

2020-04-22 10:52 UTC, projector301 commented on index.html
> +<a>검증가능한 프레젠테이션</a>에만캡슐화해야 함을 나타낸다.
에만캡슐화해야 함을 나타낸다. -> 에만 캡슐화해야 함을 나타낸다.

2020-04-22 10:52 UTC, projector301 commented on index.html
> +증명작성자가 <code>credentialSubject</code>가 아닌 <code>nonTransferable</code><a>속성</a>을 포함한
증명작성자가 -> 프루프 작성자가

2020-04-22 10:52 UTC, projector301 commented on index.html
> +이 경우 <code>credentialSubject</code> <a>속성</a>은 각<a>주체</a>의 설명 측면에서 제공하는 복합적인
각<a>주체</a>의 설명 측면에서 제공하는 복합적인 <a>속성</a>이 포함될 수 있으며-> <a>주체</a>의 여러 측면을 설명하는 <a>속성</a>들이 포함될 수 있으며

2020-04-22 10:52 UTC, projector301 commented on index.html
> +다른 사용 사례에서는 <a>검증자</a>가 <a>주체</a>와 <a>홀더</a>사이의 관계를 결정하기 위해 일정범위 외 지식(?)을 사용해야 할 수 있다.
일정범위 외 지식(?)을 -> 범위 밖 지식을
홀더 -> 보유자

2020-04-22 10:52 UTC, projector301 commented on index.html
> +<a>홀더</a>를 전혀 식별하지 않을 수 있다.
홀더 -> 보유자

2020-04-22 10:52 UTC, projector301 commented on index.html
> +다른 <a>홀더</a>에게 <a>검증가능한 크리덴셜</a>의 전체 또는 일부를 전달해야 할지도 모른다.
홀더 -> 보유자

2020-04-22 10:52 UTC, projector301 commented on index.html
> +모두 <a>검증자</a>에게 제시할 수 있는 새로운 <a>홀더</a>에게 부여함으로써 이를 허용하고 있다.
홀더 -> 보유자

2020-04-22 10:52 UTC, projector301 commented on index.html
> +        <h4>홀더가 주체를 대신하여 실행</h4>
홀더 -> 보유자

2020-04-22 10:52 UTC, projector301 commented on index.html
> +<a>홀더</a>를 지원한다.
홀더 -> 보유자

2020-04-22 10:52 UTC, projector301 commented on index.html
> +<a>발급자</a>는 <code>credentialSubject</code> <a>속성</a>에 <a>홀더</a>와
홀더 -> 보유자

2020-04-22 10:52 UTC, projector301 commented on index.html
> +<a>발급자</a>는 <a>홀더</a>가 활용하는 새로운 <a>검증가능한 크리덴셜</a>을 발급함으로써 <a>홀더</a>와
홀더 -> 보유자

2020-04-22 10:52 UTC, projector301 commented on index.html
> +<a>주체</a>는 <a>홀더</a>가 활용하는 새로운
홀더 -> 보유자

2020-04-22 10:52 UTC, projector301 commented on index.html
> +<a>검증가능한 크리덴셜</a>의 발급함으로써 <a>홀더</a>와의 관계를 표현할 수 있다.
홀더 -> 보유자

2020-04-22 10:52 UTC, projector301 commented on index.html
> +위에 열거된 매커니즘은 <a>홀더</a>와 <a>주체</a> 사이의 관계를 설명하고,
홀더 -> 보유자

2020-04-22 10:52 UTC, projector301 commented on index.html
> +<a>주체</a>와 <a>홀더</a> 사이의 검증하기 위해 사용하는 추가적인 매커니즘은 이 규격의 범위를 벗어난다.
홀더 -> 보유자

2020-04-22 10:52 UTC, projector301 commented on index.html
> +<a>주체</a>가 다른 <a>홀더</a>에게
홀더 -> 보유자

2020-04-22 10:52 UTC, projector301 commented on index.html
> +다음사항이 적용되는<a>홀더</a>에게 발급할 수 있다.
홀더 -> 보유자

2020-04-22 10:52 UTC, projector301 commented on index.html
> +<a>주체</a>가 <a>검증가능한 크리덴셜</a>이 통과된 <a>홀더</a> 일 때
홀더 -> 보유자

2020-04-22 10:52 UTC, projector301 commented on index.html
> +<a>홀더</a>는 두 개의<a>검증가능한 크리덴셜</a>을 포함하는
홀더 -> 보유자

2020-04-22 10:52 UTC, projector301 commented on index.html
> +<a>주체</a>가 기존의 <a>홀더</a>에게 원본 <a>검증가능한 크리덴셜</a>을 부여했는지를 검증할 수 있다.
홀더 -> 보유자

2020-04-22 10:52 UTC, projector301 commented on index.html
> +새로운 <a>검증가능한 프레젠테이션</a>을 생성하여 <a>검증자</a>가
<a>검증자</a>가 ->  <a>검증자</a>는

2020-04-22 11:59 UTC, projector301 commented on index.html
> +<a>검증가능한 프레젠테이션</a>에만캡슐화해야 함을 나타낸다.
```suggestion
<a>검증가능한 프레젠테이션</a>에만 캡슐화해야 함을 나타낸다.
```

2020-04-22 11:59 UTC, projector301 commented on index.html
> +<a>속성</a>이 포함될 수 있으며,
```suggestion

```

2020-04-22 12:33 UTC, minhoyoo-iotrust requested changes

2020-04-22 12:33 UTC, minhoyoo-iotrust commented on index.html
>          <section class="informative">
```suggestion
        <section class="informative" id="nonTransferable-property">
```

2020-04-22 12:33 UTC, minhoyoo-iotrust commented on index.html
>            <h5>nonTransferable Property</h5>
```suggestion
```

2020-04-22 12:33 UTC, minhoyoo-iotrust commented on index.html
> +<a>검증가능한 프레젠테이션</a>에만캡슐화해야 함을 나타낸다.
```suggestion
<a>검증가능한 프레젠테이션</a>에만 캡슐화해야 함을 나타낸다.
```

2020-04-22 12:33 UTC, minhoyoo-iotrust commented on index.html
> +프루프 작성자가 <code>credentialSubject</code>가 아닌 <code>nonTransferable</code><a>속성</a>을 포함한
```suggestion
프루프 작성자가 <code>credentialSubject</code>가 아닌 <code>nonTransferable</code> <a>속성</a>을 포함한 
```

2020-04-22 12:33 UTC, paromix commented on index.html
> +        <h4>주체 고유 식별 크리덴셜</h4>
```suggestion
        <h4>주체를 고유하게 식별하는 크리덴셜</h4>
```

2020-04-22 12:33 UTC, paromix commented on index.html
> +이 경우 <code>credentialSubject</code> <a>속성</a>은 <a>주체</a>의 여러 측면을 설명하는 <a>속성</a>들이 포함될 수 있으며
```suggestion
이 경우 <code>credentialSubject</code> <a>속성</a>은 <a>주체</a>의 여러 측면을 설명하는 
다수의 <a>속성</a>이 포함될 수 있으며
```

2020-04-22 12:33 UTC, paromix commented on index.html
> +<a>속성</a>이 포함될 수 있으며,
```suggestion
```

2020-04-22 12:33 UTC, paromix commented on index.html
> +그의 친구가 약을 수령하기 위해 처방전을 가져가야할 지 모른다.
```suggestion
그의 친구가 약을 수령하기 위해 처방전을 가져갈 수도 있다. 
```

2020-04-22 12:33 UTC, paromix commented on index.html
> +모두 <a>보유자</a>에게 제시할 수 있는 새로운 <a>홀더</a>에게 부여함으로써 이를 허용하고 있다.
```suggestion
<a>검증자</a>에게 제시할 수 있도록 함으로써 이를 가능하게 한다.
```

2020-04-22 12:33 UTC, paromix commented on index.html
> +새로운<a>검증가능한 크리덴셜</a>을 발급하고, 그 <a>검증가능한 크리덴셜</a>을
```suggestion
새로운<a>검증가능한 크리덴셜</a>을 발급하여 새로운 <a>보유자</a>에게 전달하고, 
새로운 <a>보유자</a>는 두 개의 <a>검증가능한 크리덴셜</a>을
```

2020-04-22 12:33 UTC, paromix commented on index.html
>          <pre class="example nohighlight" title="A relationship credential issued to a parent">{
```suggestion
        <pre class="example nohighlight" title="부모에게 발급된 크리덴셜  관계">{
```

2020-04-22 12:33 UTC, paromix commented on index.html
>          <pre class="example nohighlight" title="A relationship credential issued by a child">{
```suggestion
        <pre class="example nohighlight" title="아이에 의해 발급된 크리덴셜 관계">{
```

2020-04-22 12:33 UTC, paromix commented on index.html
> +위의 예에서, 아이는 <a>검증자</a>가 위의 <a>크리덴셜</a>이 제공될 경우 아이의
```suggestion
위의 예에서, 아이는 <a>검증자</a>가 위의 <a>크리덴셜</a>이 제공될 경우
```

2020-04-22 12:33 UTC, paromix commented on index.html
> +다음사항이 적용되는<a>보유자</a>에게 발급할 수 있다.
```suggestion
다음 사항이 적용되는<a>보유자</a>에게 발급할 수 있다.
```

2020-04-23 14:41 UTC, projector301 commented on index.html
> +이 경우 <code>credentialSubject</code> <a>속성</a>은 각<a>주체</a>의 설명 측면에서 제공하는 복합적인
```suggestion
이 경우 <code>credentialSubject</code> <a>속성</a>은 <a>주체</a>의 여러 측면을 설명하는 <a>속성</a>들이 포함될 수 있으며
```

2020-04-23 14:41 UTC, projector301 commented on index.html
> +<a>속성</a>이 포함될 수 있으며,
```suggestion

```

2020-04-23 14:41 UTC, projector301 commented on index.html
>          <section class="informative">
```suggestion
        <section class="informative" id="nonTransferable-property">
```

2020-04-23 14:41 UTC, projector301 commented on index.html
>            <h5>nonTransferable Property</h5>
```suggestion

```

2020-04-23 14:41 UTC, projector301 commented on index.html
> +<a>검증가능한 프레젠테이션</a>에만캡슐화해야 함을 나타낸다.
```suggestion
<a>검증가능한 프레젠테이션</a>에만 캡슐화해야 함을 나타낸다.
```

2020-04-24 13:50 UTC, daoauth approved these changes

2020-04-27 11:10 UTC, minhoyoo-iotrust requested changes

2020-04-27 11:10 UTC, paromix commented on index.html
> +        <pre class="example nohighlight" title="부모에게 발급된 크리덴셜  관계">{
```suggestion
        <pre class="example nohighlight" title="부모에게 발급된 크리덴셜 관계">{
```

2020-04-27 11:10 UTC, paromix commented on index.html
> +        <h4>발급자 허가 홀더</h4>
```suggestion
        <h4>발급자가 보유자에게 허가하기</h4>
```

2020-04-27 11:10 UTC, paromix commented on index.html
> +<a>발급자</a>가 <a>홀더</a>가 아닌
```suggestion
<a>발급자</a>가 <a>보유자</a>가 아닌 
```

2020-04-27 11:10 UTC, paromix commented on index.html
> +<a>주체</a>로 설명하는 <a>크리덴셜</a>을 <a>홀더</a>에게 부여하고
```suggestion
<a>주체</a>로 설명하는 <a>크리덴셜</a>을 <a>보유자</a>에게 부여하고
```

2020-04-27 11:10 UTC, paromix commented on index.html
> +<a>홀더</a>의 관계를 삽입할 수 있다.
```suggestion
<a>보유자</a>의 관계를 삽입할 수 있다.
```

2020-05-06 12:44 UTC, merged